#! /bin/sh
setxkbmap fr -variant oss
sxhkd &
$HOME/.config/polybar/launch.sh
$HOME/.config/wpg/wp_init.sh

bspc monitor DisplayPort-0 -d term code web music 
bspc monitor DVI-D-0 chat -d VI VII VIII IX X

bspc config border_width            0
bspc config window_gap              6

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_follows_pointer   false

bspc config focused_border_color 	\#FEFEFE
bspc config normal_border_color 	\#111824

bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

bspc rule - a Kitty desktop='^1' follow=on state=pseudo_tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a Firefox desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

windowwidth=800
windowheight=600

# screenwidth=$(xdpyinfo | awk -F’[ x]+’ ‘/dimensions:/{print $3}’)
# screenheight=$(xdpyinfo | awk -F’[ x]+’ ‘/dimensions:/{print $4}’)
# windowx=$((“$screenwidth”/2-“$windowwidth”/2))
# windowy=$((“$screenheight”/2-“$windowheight”/2))

# bspc rule -a kitty:urlpick state=floating rectangle=“$windowwidth”x”$windowheight”+”$windowx”+”$windowy” && kitty -name vimfloat -e vim $@

# bspc rule -a kitty:sxhkd_keys_help state=floating
bspc rule -a TelegramDesktop state=floating center=true
bspc rule -a Signal state=floating center=true
bspc rule -a KeePassXC state=floating center=true